const AMINO_THREE_LETTER_CODE = {
    Ala: 'A',
    Asx: 'B',
    Cys: 'C',
    Asp: 'D',
    Glu: 'E',
    Phe: 'F',
    Gly: 'G',
    His: 'H',
    Ile: 'I',
    Xle: 'J',
    Lys: 'K',
    Leu: 'L',
    Met: 'M',
    Asn: 'N',
    Pyl: 'O',
    Pro: 'P',
    Gln: 'Q',
    Arg: 'R',
    Ser: 'S',
    Thr: 'T',
    Scy: 'U',
    Val: 'V',
    Trp: 'W',
    Xxx: 'X',
    Tyr: 'Y',
    Glx: 'Z'
}

const AMINO_ACID_CODE = {
    'A': 'Ala',
    'B': 'Asx',
    'C': 'Cys',
    'D': 'Asp',
    'E': 'Glu',
    'F': 'Phe',
    'G': 'Gly',
    'H': 'His',
    'I': 'Ile',
    'J': 'Xle',
    'K': 'Lys',
    'L': 'Leu',
    'M': 'Met',
    'N': 'Asn',
    'O': 'Pyl',
    'P': 'Pro',
    'Q': 'Gln',
    'R': 'Arg', 
    'S': 'Ser',
    'T': 'Thr',
    'U': 'Scy', 
    'V': 'Val', 
    'W': 'Trp',
    'X': 'Xxx',
    'Y': 'Tyr',
    'Z': 'Glx'
}

export { AMINO_ACID_CODE, AMINO_THREE_LETTER_CODE };