const strings = {
    search: 'Search',
    submit: 'Submit',
    uploadPatents: 'Upload Patents',
    selectEpitope: 'Sequence',
    selectProtein: 'Protein Name',
    appOwnershipFooter: 'Patent Visualization App - Created by OpenPSV',
    filterByAssignee: 'Filter By Assignee',
    filterBySequencePosition: 'Filter By Sequence Position',
    minLabel: 'Min:',
    maxLabel: 'Max:',
    showAminoSequence: 'Show Amino Acid Sequence',
    claimedResidues: 'Claimed Residues',
    assignee: 'Assignee',
    patentName: 'Patent Name',
    patentNumber: 'Patent Number',
    patentFiled: 'Patent Filed',
    patentDate: 'Patent Date',
    legalOpinion: 'Legal Opinion',
    issueDate: 'Issue Date',
    tooltipSeqName: 'Text to display on the Y-axis',
    tooltipSeqExample: 'One character sequence. Example: IRNISNPN..',
    addSeq: 'Add Sequence',
    seqName: 'Sequence Name',
    add: 'Add',
    download: 'Download',
    resultsFor: 'Results for',
    editModalTitle: 'Edit Patent Data:',
    proteinNotFoundTitle: 'Error fetching protein data: ',
    proteinNotFoundDesc: 'Please return to the search page and try again.',
    proteinNotFound: 'Protein not found',
    patentHideShow: 'Hide or show patent on visualization chart',
    downloadChart: 'Download Chart',
    saveChartTooltip: 'Save image of the current state of chart',
    errorPatentEdit: 'Something went wrong editing patent',
    mentionedResidues: 'Mentioned Residues',
    mentionedResiduesTooltip: 'Residues mentioned outside claims',
    inventors: 'Inventors'
}

export default Object.freeze(strings);