name: Production Deploy
on:
  push:
      branches: 
        - prod
  workflow_dispatch:

jobs:
  deploy:
    name: prod env deploy
    runs-on: ubuntu-latest
    environment: AWS_US_EAST_1_1
    steps:
      - uses: actions/checkout@v1
      - name: use node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: run deploy script
        run: sh ./amplify_prod_deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1